### ISSUE TITLE
Would you mind adding a few examples.

### ISSUE THREAD

**Issue by joeblew99** [semakers/zoom-widget#1]
I want to try to get this working with flutter desktop and web so a few examples will make cross testing more robust

**Comment by joeblew99** [comment]
thanks for adding the example.

i will try to get it working on web and desktop.
On desktop ( mac) the touchpad is working so it should work.

**Comment by semakers** [comment]
In the next version of the package the zoom option with double tap will be added for a better interaction in the desktop apps, thank you very much for confirming that it works in web flutter

**Comment by joeblew99** [comment]
I did not think of that UX approach. Makes perfect sense.
thanks for the update.

**Comment by semakers** [comment]
You're welcome, a new version (0.1.1) with double tap zoom is already published to be able to work correctly in desktop applications either with trackpad or regular mouse.
Good day.

**Comment by joeblew99** [comment]
thanks closing...
