### ISSUE TITLE
Doble tap + drag your finger bug, also the widget start with maximun zoom.

### ISSUE THREAD

**Issue by diabloget** [semakers/zoom-widget#10]
I found this two bugs:
1. If you make doble tap and then you drag your finger to any direction as fastest as you can, the zoom "camera" will move to the left/top corner.  **Edit: If you make a "triple" tap, this bug appears**
2. Also, the other bug I found seems to be related to the first one some way, it consist in that when I open the page with the zoom widget, it starts with all the zoom posible and with the "camera" in the **left/top corner**. I will try to add a video and some code for help you the max as possible to find the solution. :) 

`
import 'package:flutter/material.dart';  
import 'package:zoom_widget/zoom_widget.dart';  
  
class Horizontalzoom{  
  static Zoom genericZoom(Stack child, double height, double width){  
    return Zoom(  
      centerOnScale: true,  
      initZoom: 0.0,  
      zoomSensibility: 7,  
      height: height,  
      width: width,  
      backgroundColor: Colors.white,  
      doubleTapZoom: true,    
      colorScrollBars: Colors.black,    
      opacityScrollBars: 0,   
      child: Material(child: child),  
    );  
  }  
}  
`

The height/width used is the device screen height/width converted to int and then multiplied for 6.0. So, basically im using a really big Zoom Widget but with the same ratio of the device screen. The child is a Stack Pane with many elements. 

Video where you can see the two bugs:
https://youtu.be/LQ0i5BhHkqE

**Comment by diabloget** [comment]
Vi que eres de méxico, creo que sería más sencillo comunicarnos en español en caso de que necesites más información de los problemas que encontré, escríbeme en cualquier situación. :)

**Comment by semakers** [comment]
Este problema se soluciono con la nueva version 2.0.0 por que se reprogramo toda la mecaninca ahora con matrices 4d :).
