### ISSUE TITLE
Programmatically zoom to point (feature request)

### ISSUE THREAD

**Issue by abulka** [semakers/zoom-widget#17]
Would be nice to be able to be able to programmatically zoom to a point, or to a box area.  This way certain areas could be zoomed into precisely e.g. by tapping on them. 

There are quite a few of these 'pan-zoom' libraries around for Javascript, for example. I understand this is probably going to far down a rabbit hole for this zoom-widget, which does a specific job. Just throwing it out there!

**Comment by semakers** [comment]
With the new version 2.0.0 you can do this with **transformationController**.

**Comment by cddqssc** [comment]
> 

Could you please provide an example about transformationController

**Comment by Achin-verma** [comment]
Yes, i am looking for the same, like on button click is it possible to zoom in and zoom out with transformationController?
if yes, then pls provide the example.
