### ISSUE TITLE
zoom auto changed from 0.0 to 1.0

### ISSUE THREAD

**Issue by lucreck** [semakers/zoom-widget#21]
First, you make a really nice widget.
Now is my case:
I init a page A with Zoom and initZoom = 0.0
but when the app navigate to a new page, and back to page A, Zoom got zoom value = 1.0
I tried so hard for why, but I can't figure it out
Thanks for supports

**Comment by narcdev** [comment]
Hey

I have the same issue ! Have you found a solution or any idea to solve it ?

Thanks

**Comment by lucreck** [comment]
> Hey
> 
> I have the same issue ! Have you found a solution or any idea to solve it ?
> 
> Thanks

I changed to Interactive Viewer
you can see here: https://api.flutter.dev/flutter/widgets/InteractiveViewer-class.html
