### ISSUE TITLE
desktop using go-flutter

### ISSUE THREAD

**Issue by joeblew99** [semakers/zoom-widget#3]
#2

**Comment by joeblew99** [comment]
Should add this Makefile so its obvious how to use it for Mobile and Desktop.

https://github.com/joeblew99/zoom-widget/blob/master/Makefile

**Comment by joeblew99** [comment]
I have to add Windows setup also for go desktop.

https://github.com/golang/go/wiki/InstallFromSource#install-c-tools

**Comment by semakers** [comment]
I already corroborate your contribution to the repository, but the official example is no longer there, neither is the Readme.md information about the desktop example.

Could you add again inside the example folder your example in a folder called desktop and the original example in a folder called mobile and information about the example desk in the Readme.md to accept your pull request?

**Comment by joeblew99** [comment]
OK. Sorry :) 
I will then make an "examples" folder and have a "mobile" and "desktop" folder to keep mobile and desktop in distinct.

**Comment by joeblew99** [comment]
Ok PR fixed i think. 
Tell me if there is anything else needed like rebasing etc, as i have not used github for PR's much...
