### ISSUE TITLE
InitTotalZoomOut not working on large images

### ISSUE THREAD

**Issue by burcus** [semakers/zoom-widget#36]
This package is very effective but initTotalZoomOut parameter not working for large images. For example when image size is 678.0, 452.0, it works fine and it initialized with full zoom out. But when image has large dimensions (2247.0, 1500.0) it initialized with a zoom. I haven't found the reason for this error yet. What can cause it?

**Comment by Achin-verma** [comment]
i am also facing the same issue, any soultions?
