### ISSUE TITLE
onTab callback method of GestureDetector doesn't work as a child of Zoom widget

### ISSUE THREAD

**Issue by lyhak570** [semakers/zoom-widget#5]
I use `GestureDetector` as a child of Zoom widget and `onTab` callback doesn't work.

```
Zoom(
    width: 1800,
    height: 1800,
    child: GestureDetector(
    onTap: () {
                  print("click");
                },
       child: Center(
        child: Text("Happy zoom!!"),
    ),),
);
```

**Comment by semakers** [comment]
Are you testing on iphone? I also gave that probe, change the gesture detector for InkWell, and now it will work perfect on Android and iPhone.

`Zoom(
    width: 1800,
    height: 1800,
    child: InkWell(
    onTap: () {
                  print("click");
                },
       child: Center(
        child: Text("Happy zoom!!"),
    ),),
);`
